# Generated by Django 5.1.7 on 2025-03-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_posts_catagery_register_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phonenumber',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
