# Generated by Django 5.1.7 on 2025-03-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_remove_posts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='img',
            field=models.URLField(max_length=300),
        ),
    ]
