# Generated by Django 5.1.7 on 2025-03-18 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_posts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
        migrations.AddField(
            model_name='posts',
            name='userId',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='delivery.register'),
            preserve_default=False,
        ),
    ]
