# Generated by Django 5.1.7 on 2025-03-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_remove_posts_user_posts_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='userId',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
