# Generated by Django 5.1.7 on 2025-03-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
