# Generated by Django 5.1.7 on 2025-03-19 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_posts_discount_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='img',
            new_name='picture',
        ),
    ]
