# Generated by Django 5.1.7 on 2025-03-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_alter_posts_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='posts',
            name='picture',
            field=models.URLField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=90),
        ),
    ]
