# Generated by Django 5.1.7 on 2025-03-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_rename_post_cartitems_item_alter_cartitems_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='cart', to='delivery.posts'),
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
